### ISSUE TITLE
Error thrown on Device#close

### ISSUE THREAD

**Issue by RyanScottLewis** [arirusso/midi-winmm#3]
Every time a device gets closed this error is thrown.

C:/Ruby192/lib/ruby/gems/1.9.1/gems/midi-winmm-0.1.2/lib/midi-winmm/map.rb:229:i
    n `winmm_func': midiOutClose: Invalid Handle (RuntimeError)
            from C:/Ruby192/lib/ruby/gems/1.9.1/gems/midi-winmm-0.1.2/lib/midi-winmm
    /output.rb:32:in`close'

**Comment by RyanScottLewis** [comment]
turns out, this only happens when open input AND output on a device.

**Comment by RyanScottLewis** [comment]
Scratch that. Output#puts no longer works on my device with the latest update. Input.gets is working fine.

**Comment by arirusso** [comment]
OK, I'm going to roll back the gem

**Comment by arirusso** [comment]
Output _was_ working for me last night.  Can you make sure that output is still working for you with version 0.1.1?

**Comment by arirusso** [comment]
Yeah... input,output, and simultaneous input/output are all working for me with 0.1.2 in win7 32

**Comment by arirusso** [comment]
it's working for me on win7 64 as well...

**Comment by RyanScottLewis** [comment]
I'll try to figure out whats goin on here today =p So confusing...

**Comment by RyanScottLewis** [comment]
Closing for extreme staleness.
